import type { NextPage } from 'next'
import Head from 'next/head'
import AccountMenu from '../components/account-menu'
import ChatMessageBox from '../components/chat/chat'
import ChatList from '../components/chat-list/chat-list'
import AppContainer from '../components/layout/app-container'
import AppLayout from '../components/layout/app-layout'
import Sidebar from '../components/layout/sidebar'
import { useState } from 'react'
import Chat from '../types/chat'

const Home: NextPage = () => {
	const [selectedChat, setSelectedChat] = useState<null | Chat>(null)

	return (
		<div className='overflow-x-hidden'>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<AppLayout>
				<AppContainer>
					<Sidebar>
						<AccountMenu />
						<ChatList onChatSelect={(chat) => setSelectedChat(chat)} />
					</Sidebar>
					<ChatMessageBox
						chat={selectedChat}
						onBackClick={() => setSelectedChat(null)}
					/>
				</AppContainer>
			</AppLayout>
		</div>
	)
}

export default Home
